name: 'hightouch_analytics_demo'
version: '1.0.0'
config-version: 2

profile: 'hightouch_analytics_demo'

model-paths: ['models']
seed-paths: ['../seeds']
macro-paths: ['macros']
test-paths: ['tests']

models:
  hightouch_analytics_demo:
    +materialized: table
    staging:
      +schema: staging
    marts:
      +schema: marts
